services:
    mariadb:
        image: mymariadb:1.0
        build: ./mariadb
        volumes:
            - "guestbook-mariadb:/var/lib/mysql:rw"
        environment:
            MARIADB_DATABASE: guestbook
            MARIADB_USER: guestbook
            MARIADB_PASSWORD_FILE: /run/secrets/mariadb-userpwd
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb-rootpwd
        secrets:
            - source: mariadb-userpwd
              target: mariadb-userpwd
              uid: "0"
              gid: "0"
              mode: 0400
            - source: mariadb-rootpwd
              target: mariadb-rootpwd
              uid: "0"
              gid: "0"
              mode: 0400
        hostname: guestbook-mariadb
        networks:
            - network-be
    apache:
        image: myapache:1.0
        build: ./apache
        depends_on:
            - mariadb
        volumes:
            - "guestbook-apache:/var/www/html:ro"
        secrets:
            - source: apachessl-crt
              target: server.crt
              uid: "0"
              gid: "0"
              mode: 0400
            - source: apachessl-key
              target: server.key
              uid: "0"
              gid: "0"
              mode: 0400
        configs:
            - source: apachessl-cfg
              target: /etc/apache2/sites-available/default-ssl.conf
              uid: "0"
              gid: "0"
              mode: 0644
        hostname: guestbook-apache
        networks:
            - network-fe
            - network-be
        ports:
            - "8080:80"
            - "8443:443"

volumes:
    guestbook-mariadb:
        name: guestbook-mariadb
    guestbook-apache:
        name: guestbook-apache

configs:
    apachessl-cfg:
        file: ./apache/default-ssl.conf

secrets:
    mariadb-userpwd:
        file: ./secrets/mariadb-userpwd.txt
    mariadb-rootpwd:
        file: ./secrets/mariadb-rootpwd.txt
    apachessl-crt:
        file: ./secrets/server.crt
    apachessl-key:
        file: ./secrets/server.key

networks:
    network-fe:
        name: network-fe
    network-be:
        name: network-be
